### ISSUE TITLE
still re-uses addresses sometimes

### ISSUE THREAD

**Issue by markblundeberg** [clifordsymack/Electron-Cash#34]
![screenshot from 2018-12-12 09-30-26](https://user-images.githubusercontent.com/36528214/49887373-00f80500-fdf1-11e8-99a8-f32627b658ff.png)

**Comment by cculianu** [comment]
I R SO SAD. :(

I will fix.  Yeah the logic for testing an address is new or not is not immune to race conditions, currently, apparently.

Is that a "change" address or a receiving address? (I presume receiving since it has the shuffled outputs)

**Comment by markblundeberg** [comment]
Yep it was receiving address. But funny, I just noticed it ALSO reused the same change addresses. That was very rare -- the only time I saw change address being reused since the first cashshuffle tests.

![screenshot from 2018-12-12 14-55-32](https://user-images.githubusercontent.com/36528214/49904106-0586e280-fe1e-11e8-8a5a-7fd84710218b.png)

e4afca2dae29e72d76a93347ffc41d407610c5f44fb941d5007f55a4236b6189

bae26a7bd5387d10a40b6b0effc1b5e1f1db5008206eb78f9fe40603419459b4

**Comment by cculianu** [comment]
Awqesome.  Thanks for the info.

Yeah this was crufty code that had race conditions under heavy use. I didn't write this code.

I have rewritten it now to be rock-solid and for race conditions to be impossible.

Fixed in commit 1d6003a32fbb1931be3deffb92b48896c825a32e

Closing issue.  If you EVER observe this again on the next test smack me in the face!
