### ISSUE TITLE
Send Tab CasShuffle Status Box

### ISSUE THREAD

**Issue by zquestz** [clifordsymack/Electron-Cash#56]
The CashShuffle status box only has a border on the top and left side which makes it look awkward on Linux, not sure if it affects other OS's.

Ideally it should either have a consistent border, or no border at all.

**Comment by cculianu** [comment]
I'll look at it today.  I suspect I may have set the border thickness to a too-small value and on retina displays it looks good due to the sub-pixel rendering they do versus non-retina it looking bad.

Will look into it.

As for no border we can do that but I'd rather have a real designer weigh in on such things.  In my opinion the border is great.  In yours it sucks.

we can vote on it, or we can get a designer.  If you feel strongly that it sucks (as you alluded to in chat) -- then please open an issue and get people to weigh in on it.  i'm not a tyrant but -- I happen to like it!

Thanks.

**Comment by cculianu** [comment]
Ok -- I hope it's fixed for you now.

---

Here is is on Mac:

<img width="979" alt="screen shot 2019-02-01 at 1 26 30 pm" src="https://user-images.githubusercontent.com/266627/52120490-20f3ba00-2625-11e9-8174-7f789464480f.png">

---

Here it is on Linux:
<img width="932" alt="screen shot 2019-02-01 at 1 27 03 pm" src="https://user-images.githubusercontent.com/266627/52120497-294bf500-2625-11e9-87f4-272c9ebb880b.png">
