### ISSUE TITLE
unusual segfault

### ISSUE THREAD

**Issue by markblundeberg** [clifordsymack/Electron-Cash#59]
Not really urgent to fix as it requires some odd steps to reproduce, but here it is:

1. Start software with imported privkey wallet as last-open wallet.
2. Do File | Open and open an HD wallet with shuffle enabled; It requests password to begin the shuffling.
3. Before entering password, close the first wallet's window.
4. Enter password, then it crashes.

I have seen both `Segmentation fault` and also `free(): invalid pointer`. :thinking: Feels like some kind of Qt cleanup bug...

**Comment by cculianu** [comment]
Oh wow nice catch.  I'll investigate.

**Comment by cculianu** [comment]
How did you manage to close the first wallet's window?  I am trying to reproduce this on macOS and the password dialog is modal and I can't close any windows.

Is this on Linux? Hmm.. let me try it on linucks.... weird that it wouldn't respect the modality of the window.

**Comment by cculianu** [comment]
Yeah, I forgot to set it to be modal for windows and linux.  I think it should be impossible to cause a crash now.

The real fix would be to figure out what's confusing Qt -- but I think it's actually a bug in PyQt because nothing we are doing in the python side should be "illegal" Qt-wise, as far as I can tell. 

Very weird bug.

**Comment by cculianu** [comment]
Fixed now.  Do let me know if you can reproduce it again.

**Comment by markblundeberg** [comment]
Haha, OK that's one way to fix it. I hate application modal windows though.

But yeah you're right -- this must by a bug in PyQt...

**Comment by cculianu** [comment]
I looked at the entire call path.  NOTHING in that call path should involve the first window, yet its closing causes a crash!  The python side seems really clean as far as that goes.

I could be wrong.  But I just can't see why it would.. CRASH.  Really.. the whole call stack ends up firing off a Qt signal in the main Qt event loop, calling `start_new_window` in `__init__.py` which ends up eventually calling the hook `on_new_window` in CashShuffle's `qt.py`.  None of this involves the first window at all.  So its death shouldn't matter... yet Qt gets confused and dies.  Very bizarre.  

I also am not a huge fan of app modal windows either but I justified it to myself in that  CashShuffle is in this half-way state when it's in the middle of figuring out if it should run on the window and it's asking for a password.  It's not a bad idea to enforce the rule "only 1 of these half-way-state windows can be up at a time" -- and making the PW dialog be app-modal ensures that.. in a heavy-handed way.

**Comment by cculianu** [comment]
I'll continue to look at this because maybe there is a weirdness elsewhere on the Python side (not in the call path per se but elsewhere) that I am missing.  The fact that Qt gets confused could be a clue... or it could be a PyQt bug.    

I'll look at it for an hour now .. and if I can figure out why this might happen, great.

**Comment by cculianu** [comment]
Funny thing is this doesn't happen at all on macOS.. :/

**Comment by cculianu** [comment]
The fun thing is this happens with regular EC too.

1. Open a wallet such as the import privkey wallet you described above.
2. Open a second wallet that has a password .. you get the install wizard popup
3. Close the first wallet
4. Complete the wizard by entering the correct password.

APP GO BOOM! (This is on Linux)

**Comment by cculianu** [comment]
You can even reproduce this outside of cashshuffle with the "watching only" popup dialog.  Close the first wallet while the second has that "this is a watching only wallet" popup....

Same thing.  Crash.

I may just elect to switch back to a window modal here for the PW dialog for CashShuffle and move this bug over to main EC since it affects all of EC.

Interestingly Electrum doesn't suffer form this so it must be some interaction spurred on by our usage of PyQt ...

**Comment by cculianu** [comment]
Update: this has now been fully addressed in EC Regular and here.
