### ISSUE TITLE
Reduce amount of shuffle information in the history tab

### ISSUE THREAD

**Issue by Mengerian** [clifordsymack/Electron-Cash#83]
Right now the shuffle tx info dominates. This makes it hard to see the information on spending and receiving transactions, which is probably more relevant to users.

One suggestion was to have the display of shuffle transactions be "toggleable", and when the toggle is "off" to replace all the Shuffle transaction with a "dash" (----)

Another suggested approach is to allow the shuffle transaction info to be collapsed and expanded for each set of "in-between" areas.

Another suggestion is to just remove shuffle transaction info from this tab altogether when the user selects "off".

**Comment by cculianu** [comment]
For the last one (remove all) it would definitely be some togglable control (show all/hide shuffle tx's). Dorks like me like to see them.  :P

Yeah sounds good.  Thanks for posting.  As soon as you mentioned it everyone was like "woah dude.. good idea" so it's definitely a winner.

**Comment by cculianu** [comment]
Ok, this has been handled in the latest commit.  

The solution I came up with is a quick right-click context menu toggle.  Anything more sophisticated would (1) take time to implement and (2) may adversely impact app performance if not done right (the history list tab is particularly sensitive since it can potentially be very large for large wallets).

Hope this is enough for now for usability.
