### ISSUE TITLE
Add blame at round 5

### ISSUE THREAD

**Issue by fyookball** [clifordsymack/Electron-Cash#99]
Kudelski found that our current code was only assigning blame for insufficient funds at round 1 but the coinshuffle paper says this should be done at phase 5, which will bolster the DOS resistance.

**Comment by cculianu** [comment]
Ok -- and  if it looks like a simple non-bug-prone change I'll do it now before release.  I haven't looked at the code in detail yet.

If it turns out to be shaky.. maybe we do it for a future version.  I'm hoping it's the former and not the latter and it would just naturally fit in there to add this phase...

**Comment by cculianu** [comment]
Ok, so I am nervous about doing this now, before release.  Reasons are:

- Risk of introducing new subtle bugs since we won't have time to test it
- Even if there are no bugs, it could end up resulting in many more failed shuffles due to slow shufflers. Asking shufflers to do another round-trip on the network after signing the tx in phase 5 (a phase that already is very slow for some shufflers) increases the risk of timeouts and failed shuffles.

There are things we can do to mitigate the second point above -- but again I fear we are rushing it with insufficient time to test.

Would you be ok if we put this on the "to-do" list and do this at some point in the future after release?

**Comment by cculianu** [comment]
Done in latest commit. I tested it and it works. 👍
